# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
  disable:
    - exhaustive
    - wrapcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/soroush/sosomi
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    # Exclude shadow checking on err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
  max-issues-per-linter: 50
  max-same-issues: 10
