# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
  disable:
    - errcheck      # TODO: Enable and fix - many unchecked errors in codebase
    - exhaustive
    - wrapcheck
    - unparam       # Too many false positives

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/soroush/sosomi
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - unparam
        - staticcheck  # Test files often have empty branches for stub logic
    # Exclude shadow checking on err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    # Exclude empty branch warnings (SA9003) - often intentional in our codebase
    - text: "SA9003:"
      linters:
        - staticcheck
  max-issues-per-linter: 50
  max-same-issues: 10
